name: xplan_flutter
description: A new flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  pull_to_refresh: ^1.5.0
  dio: 2.1.3
  json_annotation: ^2.0.0
  cached_network_image: ^1.1.0
  fluttertoast: ^3.1.0
  flutter_webview_plugin: ^0.3.5
  flutter_swiper: ^1.1.6 #banner
  flutter_staggered_grid_view: ^0.3.0 #瀑布流
  shared_preferences: ^0.5.3+4
  date_format: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.1 #自动生成model
  json_serializable: ^2.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section, 
  # like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/favorite_empty.png
    - images/menu_my.png
    - images/menu_my_pre.png
    - images/menu_news.png
    - images/menu_news_pre.png
    - images/menu_pic.png
    - images/menu_pic_pre.png
    - images/menu_video.png
    - images/menu_video_pre.png
    - images/hone_menu_icon_0.png
    - images/setting_ic_head_default.png
    - images/video_play.png
    - images/ic_category_0.png
    - images/ic_category_1.png
    - images/ic_category_2.png
    - images/ic_category_3.png
    - images/ic_category_4.png
    - images/ic_category_5.png
    - images/ic_category_6.png
    - images/ic_category_7.png
    - images/ic_category_8.png
    - images/ic_category_9.png
    - images/ic_category_10.png
    - images/ic_category_11.png
    - images/ic_category_12.png
    - images/ic_category_13.png
    - images/ic_category_14.png
    - images/ic_category_15.png
    - images/ic_category_16.png
    - images/stateview_data_error.png
    - images/stateview_net_error.png


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule
